// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-applications.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_applications_default = defineTool({
  name: "list_applications",
  title: "List applications",
  description: "List applications in the signed-in user's accessible workspaces.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).default(50).describe("Max rows to return."),
    search: z.string().trim().optional().describe("Optional name substring filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("applications").select("*").order("updated_at", { ascending: false }).limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-capabilities.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_capabilities_default = defineTool2({
  name: "list_capabilities",
  title: "List business capabilities",
  description: "List business capabilities in the signed-in user's accessible workspaces.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(50).describe("Max rows to return."),
    search: z2.string().trim().optional().describe("Optional name substring filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb2(ctx).from("capabilities").select("*").order("updated_at", { ascending: false }).limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { capabilities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-application.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_application_default = defineTool3({
  name: "create_application",
  title: "Create application",
  description: "Create a new application in a workspace the signed-in user can write to. tenant_id must be a workspace the user belongs to.",
  inputSchema: {
    tenant_id: z3.string().uuid().describe("Tenant/workspace id the application belongs to."),
    name: z3.string().trim().min(1).max(200).describe("Application display name."),
    description: z3.string().trim().max(4e3).optional().describe("Short description."),
    lifecycle: z3.enum(["proposed", "planned", "active", "deprecated", "retired"]).default("active").describe("Lifecycle stage.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ tenant_id, name, description, lifecycle }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb3(ctx).from("applications").insert({ tenant_id, name, description, lifecycle, created_by: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { application: data }
    };
  }
});

// src/lib/mcp/tools/list-audit-log.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_audit_log_default = defineTool4({
  name: "list_audit_log",
  title: "List audit log entries",
  description: "Read recent audit log entries the signed-in user is allowed to see.",
  inputSchema: {
    entity: z4.string().trim().optional().describe("Optional entity/table name filter (e.g. 'applications')."),
    limit: z4.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ entity, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb4(ctx).from("audit_log").select("*").order("at", { ascending: false }).limit(limit);
    if (entity) q = q.eq("entity", entity);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hlnkhwdmimevnkqyiasr";
var mcp_default = defineMcp({
  name: "iyarkai-eaos-mcp",
  title: "iYarKai EAOS",
  version: "0.1.0",
  instructions: "Enterprise Architecture Operating System. Query and create architecture artifacts (applications, capabilities) and read audit history for the signed-in user's workspaces.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_applications_default, list_capabilities_default, create_application_default, list_audit_log_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
